import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/java/": [
    {
      text: "Java 基础",
      icon: "discover",
      prefix: "base/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java 进阶",
      icon: "blog",
      prefix: "advance/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java 虚拟机",
      icon: "write",
      prefix: "jvm/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java框架",
      icon: "write",
      prefix: "framework/",
      collapsible: true,
      children: "structure",
    },
  ],
  "/java/other/": [
    "JdkVersion",
    {
      text: "Maven",
      icon: "discover",
      prefix: "maven/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Gradle",
      icon: "discover",
      prefix: "gradle/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java问题定位",
      icon: "java",
      prefix: "locateproblem/",
      collapsible: true,
      children: "structure",
    },
  ],
  "/frontweb/": [
    {
      text: "Vue",
      icon: "vue",
      prefix: "vue/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Vite",
      icon: "vue",
      prefix: "vite/",
      collapsible: true,
      children: [],
    },
    {
      text: "ECMAScript 5",
      icon: "write",
      prefix: "es5/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "ECMAScript 6",
      icon: "blog",
      prefix: "es6/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "TypeScript",
      icon: "typescript",
      prefix: "typeScript/",
      collapsible: true,
      children: "structure",
    },
  ],

  "/designpattern/": [
    {
      text: "java设计模式",
      icon: "java",
      prefix: "",
      collapsible: true,
      children: "structure",
    },
  ],
  "/cpp/": [
    {
      text: "基础语法学习",
      icon: "app",
      prefix: "study/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "其他",
      icon: "app",
      prefix: "other/",
      collapsible: true,
      children: "structure",
    },
  ],
  "/other/": [
    {
      text: "Git",
      icon: "git",
      prefix: "git/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Linux",
      icon: "linux",
      prefix: "linux/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "数据库",
      icon: "repo",
      prefix: "database/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "MarkDown",
      icon: "markdown",
      prefix: "markdown/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "工具软件",
      icon: "software",
      prefix: "tools/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "小组分享",
      icon: "share",
      prefix: "training/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "随笔分享",
      icon: "share",
      prefix: "essay/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "web",
      icon: "share",
      prefix: "web/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "分布式微服务",
      icon: "share",
      prefix: "distributeservice/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "OAuth2.0",
      icon: "share",
      prefix: "oauth2/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Docker",
      icon: "ubuntu",
      prefix: "docker/",
      collapsible: true,
      children: "structure",
    },
  ],
});
